#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main_cp");
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("header1_cp");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_header1_cp(cod([]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["header1_cp"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("attr", cod([("id", "map")])), ("style", cod([("height", "100%")]))]))));
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "catgselect hide-on-med-and-down"), ("style", cod([("padding-bottom", "0px")]))]))));
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("id", "maincontrol"), ("style", cod([("margin-bottom", "-30px")]))]))));
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("cp_filterform");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_cp_filterform(cod([]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["cp_filterform"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("id", "maincontrol1"), ("style", cod([("display", "none")]))]))));
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "col l1 s1 m1")]))));
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("style", cod([("padding", "8px"), ("margin-bottom", "4px"), ("padding-left", "0px"), ("margin-left", "-20px")]))]))));
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("icon1");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_icon1(cod([("img", "photo/plus1.png"), ("class", "pointer"), ("attr", cod([("onclick", "minimaxifilter(2);")]))]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["icon1"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "modal"), ("id", "commoncats")]))));
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "modal-content")]))));
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("id", "bcard1"), ("class", "modal bottom-sheet")]))));
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "modal-content")]))));
outpvar.cur.fcalldata["main_cp"].addtext("Mohit");
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "modal-footer")]))));
outpvar.cur.fcalldata["main_cp"].addtext("Saini");
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "modal"), ("id", "providerform"), ("style", cod([("padding", "20px")]))]))));
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("style", cod([("margin", "10px")]))]))));
outpvar.cur.fcalldata["main_cp"].open(htmlnode("form", extentattrs(cod([("data", cod([("onsubmit", "sreq"), ("bobj", ""), ("action", "providerinfo"), ("restext", "Submitted")]))]))));
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("style", cod([("font-size", "20px")]))]))));
outpvar.cur.fcalldata["main_cp"].addtext("Fill the provider's Details");
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_input1(cod([("label", "Catageroy"), ("id", "form_catg")]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_input1(cod([("label", "Sub-Catageroy"), ("id", "form_subcatg")]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_input1(cod([("label", "Provider"), ("id", "form_prov")]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_input1(cod([("label", "Email"), ("id", "form_email")]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_input1(cod([("label", "Phone"), ("id", "form_phone")]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_input1(cod([("label", "Address"), ("id", "form_address"), ("aclass", "col l12")]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_input1(cod([("label", "Link to Website"), ("id", "form_web"), ("aclass", "col l12")]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_input1(cod([("label", "Link to Class Sechedule"), ("id", "form_sechedule"), ("aclass", "col l12")]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("button1");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_button1(cod([("name", "Submit"), ("attr", cod([("type", "submit")]))]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["button1"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "modal"), ("id", "contactusform"), ("style", cod([("padding", "20px")]))]))));
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("cp_contactus_form");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_cp_contactus_form(cod([]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["cp_contactus_form"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "modal"), ("id", "ourstory"), ("style", cod([("padding", "20px")]))]))));
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("cp_our_story");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_cp_our_story(cod([]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["cp_our_story"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "modal modal-fixed-footer"), ("id", "searchform"), ("style", cod([("padding", "0")]))]))));
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "modal-content"), ("style", cod([("padding", "0px"), ("margin", "0px")]))]))));
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].open(htmlnode("div", extentattrs(cod([("class", "modal-footer"), ("attr", cod([("align", "right")]))]))));
outpvar.cur.fcalldata["main_cp"].cur.addfcdata("button2");
outpvar.cur.fcalldata["main_cp"].addchilds(newtag_button2(cod([("aclass", "realyes modal-action modal-close"), ("text", "Go")]), ginp, outpvar.cur.fcalldata["main_cp"].cur.fcalldata["button2"].root.content).root.content);
outpvar.cur.fcalldata["main_cp"].close();
outpvar.cur.fcalldata["main_cp"].close();
outpvar.addchilds(newtag_main_cp(cod([("js", ["js/index.js?reload", "https://maps.googleapis.com/maps/api/js?signed_in=true&libraries=drawing,places&callback=initMap"])]), ginp, outpvar.cur.fcalldata["main_cp"].root.content).root.content);