#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main1");
outpvar.cur.fcalldata["main1"].cur.addfcdata("header1_cp");
outpvar.cur.fcalldata["main1"].addchilds(newtag_header1_cp(cod([]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["header1_cp"].root.content).root.content);
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("attr", cod([("id", "map")])), ("style", cod([("height", "100%")]))]))));
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("class", "catgselect")]))));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("id", "maincontrol")]))));
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("id", "maincontrol1"), ("style", cod([("display", "none")]))]))));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("class", "col l1 s1 m1")]))));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("style", cod([("padding", "8px"), ("margin-bottom", "4px"), ("padding-left", "0px"), ("margin-left", "-20px")]))]))));
outpvar.cur.fcalldata["main1"].cur.addfcdata("icon1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_icon1(cod([("img", "photo/plus1.png"), ("class", "pointer"), ("attr", cod([("onclick", "minimaxifilter(2);")]))]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["icon1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("id", "bcard1"), ("class", "modal bottom-sheet")]))));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("class", "modal-content")]))));
outpvar.cur.fcalldata["main1"].addtext("Mohit");
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("class", "modal-footer")]))));
outpvar.cur.fcalldata["main1"].addtext("Saini");
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("class", "modal"), ("id", "providerform"), ("style", cod([("padding", "20px")]))]))));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("style", cod([("margin", "10px")]))]))));
outpvar.cur.fcalldata["main1"].open(htmlnode("form", extentattrs(cod([("data", cod([("onsubmit", "sreq"), ("bobj", ""), ("action", "providerinfo"), ("restext", "Submitted")]))]))));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("style", cod([("font-size", "20px")]))]))));
outpvar.cur.fcalldata["main1"].addtext("Fill the provider's Details");
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("class", "row")]))));
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1(cod([("label", "Catageroy"), ("id", "form_catg")]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1(cod([("label", "Sub-Catageroy"), ("id", "form_subcatg")]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1(cod([("label", "Provider"), ("id", "form_prov")]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1(cod([("label", "Provider's Email"), ("id", "form_email")]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1(cod([("label", "Provider's Phone"), ("id", "form_phone")]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1(cod([("label", "Provider's Address"), ("id", "form_address"), ("aclass", "col l12")]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1(cod([("label", "Link to Website"), ("id", "form_web"), ("aclass", "col l12")]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1(cod([("label", "Link to Class Sechedule"), ("id", "form_sechedule"), ("aclass", "col l12")]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([]))));
outpvar.cur.fcalldata["main1"].cur.addfcdata("button1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_button1(cod([("name", "Submit"), ("attr", cod([("type", "submit")]))]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["button1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("class", "modal"), ("id", "contactusform"), ("style", cod([("padding", "20px")]))]))));
outpvar.cur.fcalldata["main1"].cur.addfcdata("cp_contactus_form");
outpvar.cur.fcalldata["main1"].addchilds(newtag_cp_contactus_form(cod([]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["cp_contactus_form"].root.content).root.content);
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs(cod([("class", "modal"), ("id", "ourstory"), ("style", cod([("padding", "20px")]))]))));
outpvar.cur.fcalldata["main1"].cur.addfcdata("cp_our_story");
outpvar.cur.fcalldata["main1"].addchilds(newtag_cp_our_story(cod([]), ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["cp_our_story"].root.content).root.content);
outpvar.cur.fcalldata["main1"].close();
outpvar.addchilds(newtag_main1(cod([("js", ["js/jquery-ui.js", "js/index.js"]), ("title", "Class Pundit")]), ginp, outpvar.cur.fcalldata["main1"].root.content).root.content);