#This code is auto generated code, don't Edit it 
outpvar.cur.addfcdata("main1");
outpvar.cur.fcalldata["main1"].cur.addfcdata("header1_cp");
outpvar.cur.fcalldata["main1"].addchilds(newtag_header1_cp({}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["header1_cp"].root.content).root.content);
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"attr": {"id": "map"}, "style": {"height": "100%"}})));
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"class": "catgselect"})));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"id": "maincontrol"})));
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"id": "maincontrol1", "style": {"display": "none"}})));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"class": "row"})));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"class": "col l1 s1 m1"})));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"style": {"padding": "8px", "margin-bottom": "4px", "padding-left": "0px", "margin-left": "-20px"}})));
outpvar.cur.fcalldata["main1"].cur.addfcdata("icon1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_icon1({"img": "photo/plus1.png", "class": "pointer", "attr": {"onclick": "minimaxifilter(2);"}}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["icon1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"id": "bcard1", "class": "modal bottom-sheet"})));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"class": "modal-content"})));
outpvar.cur.fcalldata["main1"].addtext("Mohit");
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"class": "modal-footer"})));
outpvar.cur.fcalldata["main1"].addtext("Saini");
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"class": "modal", "id": "providerform", "style": {"padding": "20px"}})));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"style": {"margin": "10px"}})));
outpvar.cur.fcalldata["main1"].open(htmlnode("form", extentattrs({"data": {"onsubmit": "sreq", "bobj": "", "action": "providerinfo", "restext": "Submitted"}})));
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"style": {"font-size": "20px"}})));
outpvar.cur.fcalldata["main1"].addtext("Fill the provider's Details");
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"class": "row"})));
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1({"label": "Catageroy", "id": "form_catg"}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1({"label": "Sub-Catageroy", "id": "form_subcatg"}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1({"label": "Provider", "id": "form_prov"}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1({"label": "Provider's Email", "id": "form_email"}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1({"label": "Provider's Phone", "id": "form_phone"}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1({"label": "Provider's Address", "id": "form_address", "aclass": "col l12"}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1({"label": "Link to Website", "id": "form_web", "aclass": "col l12"}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].cur.addfcdata("input1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_input1({"label": "Link to Class Sechedule", "id": "form_sechedule", "aclass": "col l12"}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["input1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({})));
outpvar.cur.fcalldata["main1"].cur.addfcdata("button1");
outpvar.cur.fcalldata["main1"].addchilds(newtag_button1({"name": "Submit", "attr": {"type": "submit"}}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["button1"].root.content).root.content);
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"class": "modal", "id": "contactusform", "style": {"padding": "20px"}})));
outpvar.cur.fcalldata["main1"].cur.addfcdata("cp_contactus_form");
outpvar.cur.fcalldata["main1"].addchilds(newtag_cp_contactus_form({}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["cp_contactus_form"].root.content).root.content);
outpvar.cur.fcalldata["main1"].close();
outpvar.cur.fcalldata["main1"].open(htmlnode("div", extentattrs({"class": "modal", "id": "ourstory", "style": {"padding": "20px"}})));
outpvar.cur.fcalldata["main1"].cur.addfcdata("cp_our_story");
outpvar.cur.fcalldata["main1"].addchilds(newtag_cp_our_story({}, ginp, outpvar.cur.fcalldata["main1"].cur.fcalldata["cp_our_story"].root.content).root.content);
outpvar.cur.fcalldata["main1"].close();
outpvar.addchilds(newtag_main1({"js": ["js/jquery-ui.js", "js/index.js"], "title": "Class Pundit"}, ginp, outpvar.cur.fcalldata["main1"].root.content).root.content);